export const userListMock = [
  {
    age: 30,
    birthday: 'string',
    cardId: 'string',
    createTime: '2021-05-12T06:51:05.937Z',
    customerId: 0,
    gender: 0,
    id: 11,
    medicalHistories: [
      {
        createTime: '2021-05-12T06:51:05.937Z',
        customerId: 0,
        description: 'string',
        diseaseName: 'string',
        dragUserId: 0,
        id: 0,
        isNormal: 0,
        merchantCode: 'string',
        name: 'string',
        type: 'string',
      },
    ],
    merchantCode: 'string',
    mobile: '150****2356',
    name: '李晓华',
    verified: true,
  },
  {
    age: 31,
    birthday: 'string',
    cardId: 'string',
    createTime: '2021-05-12T06:51:05.937Z',
    customerId: 0,
    gender: 0,
    id: 12,
    medicalHistories: [
      {
        createTime: '2021-05-12T06:51:05.937Z',
        customerId: 0,
        description: 'string',
        diseaseName: 'string',
        dragUserId: 0,
        id: 0,
        isNormal: 0,
        merchantCode: 'string',
        name: 'string',
        type: 'string',
      },
    ],
    merchantCode: 'string',
    mobile: '150****2356',
    name: '李晓华1',
    verified: true,
  },
  {
    age: 32,
    birthday: 'string',
    cardId: 'string',
    createTime: '2021-05-12T06:51:05.937Z',
    customerId: 0,
    gender: 1,
    id: 13,
    medicalHistories: [
      {
        createTime: '2021-05-12T06:51:05.937Z',
        customerId: 0,
        description: 'string',
        diseaseName: 'string',
        dragUserId: 0,
        id: 0,
        isNormal: 0,
        merchantCode: 'string',
        name: 'string',
        type: 'string',
      },
    ],
    merchantCode: 'string',
    mobile: '150****2356',
    name: '李晓华2',
    verified: true,
  },
]
